# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: QGIS Anwendergruppe Schweiz / Groupe d'utilisateurs QGIS Suisse
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: QGISCH
github_username:  qgis-ch

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

defaults:
  - scope:
      path: "assets/img"
    values:
      image: true
  - scope:
      path: "de"
    values:
      lang: "de"
      layout: "plain-de"
      description: >-
        QGIS ist eine GIS Plattform bestehend aus den Komponenten Desktop-GIS,
        Server-GIS, Web-GIS Client und Mobile-GIS. QGIS Desktop ist eine
        benutzerfreundliche GIS Anwendung für das Erstellen von Karten und Layouts,
        das Bearbeiten und Analysieren von Geodaten. 
        Die QGIS Anwendergruppe Schweiz ist ein Verein der QGIS Anwender in der
        Schweiz. Es ist ein Verein im Sinne des schweizerischen Zivilgesetzbuches
        gemäss Artikel 60-79. Derzeit gibt es circa 120 Mitglieder aus Behörden,
        Firmen, Universitäten und Einzelpersonen.

  - scope:
      path: "fr"
    values:
      lang: "fr"
      layout: "plain-fr"
      description: >-
        QGIS est une plate-forme SIG constitué de composants bureautique, serveur,
        web et mobile. QGIS Desktop est une application SIG conviviale pour créer
        des cartes et des mises en page, l'édition et l'analyse des données spatiales.
        Le Groupe d'utilisateurs QGIS est une association des utilisateurs QGIS
        en Suisse. Le Groupe d'utilisateurs QGIS est une association selon les
        art. 60-79 du Code Civil (CC) suisse. Il compte actuellement environ 120
        membres issus des pouvoirs publics, des entreprises, des universités et
        des individus.
        

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - /scripts/
  - README.md
