name: Build and deploy website
run-name: ${{ github.repository }} is built and deployed
on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 22 * * 0"

jobs:
  Jekyll:
    name: Build Jekyll site and deploy it to the web server
    runs-on: ubuntu-latest
    steps:
      - run: echo "Branch is ${{ github.ref }} in repository ${{ github.repository }} is built and deployed."
      
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Setup Ruby environment
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: true
          cache-version: 0

      - name: Build website with Jekyll
        run: bundle exec jekyll build --baseurl "${{ steps.pages.outputs.base_path }}"
        env:
          JEKYLL_ENV: production

      - name: Copy the files to the server using rsync
        uses: burnett01/rsync-deployments@6.0.0
        with:
          switches: -avxP --delete --exclude="/invoice" --exclude="/invoice-usermeeting" --exclude="/qgisuser"
          path: _site/*
          remote_path: /var/www/sites/qgisch
          remote_host: ${{ secrets.HOST }}
          remote_user: ${{ secrets.USERNAME }}
          remote_key: ${{ secrets.SSH_PRIVATE_KEY }}
