name: Build and deploy website
run-name: ${{ github.repository }} is built and deployed
on:
  push:
    branches:
      - main
jobs:
  Jekyll:
    name: Build Jekyll site and deploy it to the web server
    runs-on: ubuntu-latest
    steps:
      - run: echo "Branch is ${{ github.ref }} in repository ${{ github.repository }} is built and deployed."
      
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Setup Python environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install Python packages
        run: |
          python -m pip install --upgrade pip
          pip install jinja2

      - name: Write courses pages
        run: |
          cd ./scripts/; ./write-courses.py

      - name: Build website with Jekyll
        uses: jerryjvl/jekyll-build-action@v1

      - name: Copy the files to the server using rsync
        uses: burnett01/rsync-deployments@6.0.0
        with:
          switches: -avxP --delete
          path: _site/*
          remote_path: /var/www/sites/qgisch
          remote_host: ${{ secrets.HOST }}
          remote_user: ${{ secrets.USERNAME }}
          remote_key: ${{ secrets.SSH_PRIVATE_KEY }}
